# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b30fd4fe486150bd5d6fe905f545354caf1ce14fdb0b76fe81b0abe4a7a6aa281e7463d33fe801412350a3883603d60494da34f545570ab63586ffe689827aff

test:
  secret_key_base: d4026ff0dde4d0c2fa40be6709270b2a946096071898a33460d036bf8a2645ec74ee7e017e00cfe772c0ae09169da93eaf740eb1aa542f903ff19865b8db2d68

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
